"""Add unique constraint to title in tasks

Revision ID: 9cf271e7670a
Revises: 24e34145e9b3
Create Date: 2024-11-21 00:35:14.873072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf271e7670a'
down_revision: Union[str, None] = '24e34145e9b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tasks', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    # ### end Alembic commands ###
